//! The four furniture-shop tools, defined once.
//!
//! Both surfaces use this module, so they cannot drift:
//!
//! - `bin/mcp.rs` — MCP server (schemas generated by `rmcp` macros)
//! - `agent.rs` — the in-app assistant (schemas sent to Azure OpenAI)
//!
//! The descriptions below are the load-bearing part. They tell the model what
//! the shop's API *cannot* do — no free-text, price, or colour search — so it
//! fetches plain results and applies that judgement itself instead of expecting
//! the API to understand "cheap" or "blue".

use serde_json::{json, Value};

use crate::external_api::ExternalApiClient;

/// Upstream's cap. The catalogue is 762 items, so this fetches everything.
pub const MAX_LIMIT: u32 = 1000;

pub const SEARCH_TOOL: &str = "search_furniture_catalogue";
pub const PRODUCT_TOOL: &str = "get_furniture_product";
pub const BALANCE_TOOL: &str = "check_shop_balance";
pub const PROPOSE_TOOL: &str = "propose_furniture_purchase";

pub const SEARCH_DESC: &str = "Lists furniture from the shop's 762-item catalogue, optionally \
narrowed to one exact category, returning each item's ID, name, price, colours and dimensions \
so you can filter the results yourself. This endpoint CANNOT search by price, colour, style, \
keyword or any free-text description — to answer a request like \"a cheap blue chair\", list \
the relevant category and judge the returned data yourself. Valid categories, which must match \
exactly: Bar furniture, Beds, Bookcases & shelving units, Cabinets & cupboards, Café furniture, \
Chairs, Chests of drawers & drawer units, Children's furniture, Nursery furniture, Outdoor \
furniture, Room dividers, Sideboards buffets & console tables, Sofas & armchairs, TV & media \
furniture, Tables & desks, Trolleys, Wardrobes.";

pub const PRODUCT_DESC: &str = "Fetches full details of one furniture item by its exact item_id. \
Use this only after search_furniture_catalogue has given you an ID — it cannot find products by \
name. Search results already include price, category, colours and dimensions, so call this only \
when you need the product page link or want to confirm a specific item still exists.";

pub const BALANCE_DESC: &str = "Returns the current spending balance at the furniture shop. Call \
it before proposing a purchase and again afterwards, since every order debits the balance \
immediately. Takes no arguments — there is one account, fixed by the shop credentials.";

pub const PROPOSE_DESC: &str = "Proposes a purchase for the user to confirm. This does NOT buy \
anything and does NOT spend money — it works out the exact item, quantity, unit price and total, \
and shows the user a confirmation panel with a Confirm button. Only the user's click actually \
places the order. Call this whenever the user asks to buy something; you do not need permission \
first, because the confirmation step IS the permission. It returns the totals and whether the \
balance covers them, so you can tell the user what they are about to spend. Propose only one \
purchase per reply.";

/// Tool definitions in OpenAI function-calling shape.
///
/// **None of these can spend money.** The most a model can do is *propose* a
/// purchase; the order itself is placed by a separate, deterministic call that
/// only the user's Confirm click triggers.
///
/// Note these are deliberately **not** `strict`: strict mode requires every
/// property to appear in `required`, which would make `category` and `limit`
/// mandatory and remove the "search the whole catalogue" option.
pub fn definitions() -> Vec<Value> {
    let mut tools = vec![
        json!({
            "type": "function",
            "function": {
            "name": SEARCH_TOOL,
            "description": SEARCH_DESC,
            "parameters": {
                "type": "object",
                "properties": {
                    "category": {
                        "type": "string",
                        "description": "Exact category name to filter by (case-insensitive). \
        Partial names like \"Sofas\" or \"bed\" match nothing. Omit to list the whole catalogue."
                    },
                    "limit": {
                        "type": "integer",
                        "description": "Maximum products to return (1-1000). Defaults to all."
                    }
                },
                "required": []
            }
            }
        }),
        json!({
            "type": "function",
            "function": {
                "name": PRODUCT_TOOL,
                "description": PRODUCT_DESC,
                "parameters": {
                    "type": "object",
                    "properties": {
                        "item_id": {
                            "type": "string",
                            "description": "The exact item_id from a search result, e.g. \"00368814\"."
                        }
                    },
                    "required": ["item_id"]
                }
            }
        }),
        json!({
            "type": "function",
            "function": {
                "name": BALANCE_TOOL,
                "description": BALANCE_DESC,
                "parameters": { "type": "object", "properties": {}, "required": [] }
            }
        }),
    ];

    tools.push(json!({
        "type": "function",
        "function": {
            "name": PROPOSE_TOOL,
            "description": PROPOSE_DESC,
            "parameters": {
                "type": "object",
                "properties": {
                    "item_id": {
                        "type": "string",
                        "description": "The exact item_id of the product to propose buying."
                    },
                    "quantity": {
                        "type": "integer",
                        "description": "How many units. Defaults to 1."
                    }
                },
                "required": ["item_id"]
            }
        }
    }));

    tools
}

/// Runs a tool and returns its JSON result.
///
/// `Err` carries a message meant for the model, not the end user — callers send
/// it back as an errored tool result so the model can correct itself.
pub async fn execute(
    client: &ExternalApiClient,
    name: &str,
    input: &Value,
) -> Result<String, String> {
    match name {
        SEARCH_TOOL => search(client, input).await,
        PRODUCT_TOOL => product(client, input).await,
        BALANCE_TOOL => balance(client).await,
        PROPOSE_TOOL => propose(client, input).await,
        // Defence in depth: there is deliberately no branch that places an
        // order. Even a hallucinated tool name cannot spend money here.
        other => Err(format!("no such tool: {other}")),
    }
}

/// Maps a caller-supplied category onto a real one, or explains the options.
///
/// Upstream returns an empty list for an unrecognised category —
/// indistinguishable from "nothing in stock", and exactly the kind of non-error
/// a model reports to the user as fact. This makes a wrong guess loud and
/// self-correcting by naming every valid value.
pub async fn resolve_category(
    client: &ExternalApiClient,
    requested: &str,
) -> Result<String, String> {
    let categories = client.categories().await.map_err(|e| e.to_string())?;
    let wanted = requested.trim().to_lowercase();

    match categories.iter().find(|c| c.to_lowercase() == wanted) {
        Some(matched) => Ok(matched.clone()),
        None => Err(format!(
            "\"{requested}\" is not a category in this shop. Categories must match exactly \
             (case-insensitive). Valid categories: {}. Retry with one of these, or omit the \
             category to search the whole catalogue.",
            categories.join(", ")
        )),
    }
}

async fn search(client: &ExternalApiClient, input: &Value) -> Result<String, String> {
    let category = match input.get("category").and_then(Value::as_str).map(str::trim) {
        Some(c) if !c.is_empty() => Some(resolve_category(client, c).await?),
        _ => None,
    };

    let limit = input
        .get("limit")
        .and_then(Value::as_u64)
        .map(|l| (l as u32).clamp(1, MAX_LIMIT))
        .unwrap_or(MAX_LIMIT);

    let products = client
        .search_index(category.as_deref(), limit, 0)
        .await
        .map_err(|e| e.to_string())?;

    let items: Vec<Value> = products
        .iter()
        .map(|p| {
            json!({
                "item_id": p.item_id,
                "product_name": p.product_name,
                "price": p.price,
                "category": p.category,
                "colours": p.colours.clone().unwrap_or_default(),
                "width_cm": p.width,
                "height_cm": p.height,
                "depth_cm": p.depth,
            })
        })
        .collect();

    // Say so when the page is full — a truncated list that looks complete is
    // how a model ends up confidently reporting a partial answer as the whole.
    let maybe_truncated = items.len() as u32 == limit && limit < MAX_LIMIT;

    Ok(json!({
        "count": items.len(),
        "filtered_by_category": category,
        "possibly_truncated": maybe_truncated,
        "products": items,
    })
    .to_string())
}

async fn product(client: &ExternalApiClient, input: &Value) -> Result<String, String> {
    let item_id = input
        .get("item_id")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| "item_id is required".to_string())?;

    let p = client.product(item_id).await.map_err(|e| e.to_string())?;

    // `image_url` holds ~60KB of base64 JPEG, not a URL. Report whether a photo
    // exists; never put the bytes into the model's context.
    Ok(json!({
        "item_id": p.item_id,
        "product_name": p.product_name,
        "price": p.price,
        "category": p.category,
        "colours": p.colours.unwrap_or_default(),
        "width_cm": p.width,
        "height_cm": p.height,
        "depth_cm": p.depth,
        "product_page": p.link,
        "has_image": p.image_url.is_some(),
    })
    .to_string())
}

async fn balance(client: &ExternalApiClient) -> Result<String, String> {
    let user = client.balance().await.map_err(|e| e.to_string())?;

    Ok(json!({
        "user_id": user.user_id,
        "account_name": user.name,
        "balance": user.balance,
    })
    .to_string())
}

/// Prices a purchase and hands it to the user to confirm. **Places no order.**
///
/// The `idempotency_key` minted here travels to the browser and back on the
/// confirm call, so a double-clicked Confirm button cannot charge twice.
async fn propose(client: &ExternalApiClient, input: &Value) -> Result<String, String> {
    let item_id = input
        .get("item_id")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| "item_id is required".to_string())?;

    let quantity = input.get("quantity").and_then(Value::as_i64).unwrap_or(1);
    if quantity < 1 {
        return Err("quantity must be at least 1".to_string());
    }

    let product = client.product(item_id).await.map_err(|e| e.to_string())?;
    let user = client.balance().await.map_err(|e| e.to_string())?;

    let total = product.price * quantity as f64;
    let affordable = total <= user.balance;

    Ok(json!({
        "status": "awaiting_user_confirmation",
        "nothing_has_been_bought": true,
        "item_id": product.item_id,
        "product_name": product.product_name,
        "quantity": quantity,
        "unit_price": product.price,
        "total": total,
        "balance": user.balance,
        "balance_after": user.balance - total,
        "affordable": affordable,
        "idempotency_key": uuid::Uuid::new_v4().to_string(),
        "note": if affordable {
            "A confirmation panel is now showing to the user. Tell them what they are about to \
             buy and the total, and that nothing is charged until they press Confirm."
        } else {
            "The balance does NOT cover this. Tell the user plainly rather than encouraging them \
             to confirm."
        },
    })
    .to_string())
}
